version: 2
registries:
  one-artifactory:
    type: maven-repository
    url: https://one.hitachivantara.com
    username: ${{secrets.PENTAHO_CICD_ONE_USER}}
    password: ${{secrets.PENTAHO_CICD_ONE_KEY}}
updates:
- package-ecosystem: maven
  directory: "/"
  registries: "*"
  schedule:
    interval: daily
  ignore:
    - dependency-name: org.apache.maven:*
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
